import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillGithub} from 'react-icons/ai'
import {BsArrowRight} from "react-icons/bs"
// import pdf from "../public/Akshit_Resume.pdf"

import Image from 'next/image'
import avatar2 from "../public/avatar2.png"

import lang from '../public/lang.png'
import machine from '../public/machine.png'
import tools from '../public/tools.png'

import gdc from "../public/gdc-logo.png"
import club from "../public/club.png"
import ais from "../public/ais.png"

import reading from "../public/reading.png"
import gym from "../public/physical-activity.png"
import french from "../public/french.png"
import muay from "../public/muay-thai.png"
import dance from "../public/dancing.png"
import art from "../public/digital-art.png"

import {useState} from 'react'
import Link from 'next/link'
import SideNavBar from '../components/SideNavbar'
import Chips from '../components/Chips'
import Blocks from '../components/Blocks'
import Course from '../components/Course'
import Carousel from '../components/Carousel'
import Bullet from '../components/Bullet'
import ViewBtn from '../components/ViewBtn'
import SectionPortfolio from '../components/sections/section-portfolio'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div id="home" className={darkMode ? "dark" : ""}>
      <Head>
        <title>Akshit Keoliya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}/>
      </Head>
      <SideNavBar/>

      <div className="lg:hidden fixed top-0 w-full z-10 bg-white dark:bg-[#1f1f1f]">
        <div className=" p-5 flex justify-end dark:text-white">
        <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" />
        </div>
      </div>

      <main className=' bg-white px-5 md:px-5 lg:ml-20 lg:px-40 dark:bg-[#1f1f1f]'>

        {/* HOMEPAGE SECTION */}

        <nav className='hidden lg:block fixed z-10 top-10 right-4 lg:right-10 justify-between dark:text-white'>
          <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=' cursor-pointer text-2xl
              '/></li>
          </ul>
        </nav>

        <section className='lg:pt-20 pt-16 min-h-screen md:min-h-fit'>
        
        {/* Navigation Section */}
        
          {/* Introduction */}

          <div className='flex justify-center mx-auto'>
          <div className='lg:hidden relative rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading='eager' priority='true' />
          </div>
          </div>

          <div className=' flex justify-center items-center mx-auto md:mb-12 md:pb-10'>
          <div className='hidden lg:block relative bg-gradient-to-b from-my-text-light to-my-text-dark rounded-full w-80 h-80 lg:mt-10 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading='eager' priority='true' />
          </div>
          
          <div className='px-20'>
          <div className=' text-center p-5 lg:p-10 font-productsans'>
            <h2 className=' text-4xl lg:text-6xl py-2 text-my-text-light md:text-6xl dark:text-my-text-dark'>Akshit Abhay Keoliya</h2>
            <h3 className=' text-xl pt-2 md:text-3xl dark:text-white'>Machine Learning Enthusiast and Developer</h3>
            <p className=' text-md py-5 lg:leading-8 text-gray-800v md:text-xl max-w-xl mx-auto dark:text-gray-200'>
            Completing my master<span>&apos;</span>s in Computer Science at 
            <span className='text-[#0b57d0] dark:text-[#a8c7fa]'><a href='https://www.usc.edu/'> USC</a></span>.
            <br></br>
            Excited to apply my knowledge to real-world problems and help organizations improve their operations and decision-making through machine learning!
              </p>

              <div className='pt-5'>
              <a className=' bg-my-text-light dark:bg-my-text-dark text-white dark:text-gray-800
              text-2xl
              font-productsans px-8 py-4 rounded-full' 
              href='/portfolio/Akshit_Resume.pdf' target="_blank" rel="noreferrer">
                Curriculum Vitae
              </a>
              </div>

          </div>

          {/* Contacts */}

          <div className=' text-5xl flex justify-center gap-10 py-8 text-gray-600 dark:text-gray-400'>
            <a href='https://www.linkedin.com/in/akshit-keoliya'><AiFillLinkedin /></a>  
            <a href='https://github.com/Leonardo-daVinci'><AiFillGithub /></a>
            <a href='https://twitter.com/AkshitAbhay'><AiFillTwitterCircle /></a>
            <a href='https://www.instagram.com/machine.learning.chef'><AiFillInstagram /></a>
          </div>
          </div>

          </div>

          {/* Image */}

          {/* <div className='lg:hidden relative mx-auto bg-gradient-to-b from-my-text-light to-my-text-dark rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading="eager" priority='true' />
          </div> */}

        </section>

        {/* SKILLS SECTION */}

        <section>
          <div id="my-skills" className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-5 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark'>My skills</h3>
              <p className=' text-md py-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
              I have a strong background in mathematics and computer science and 
              have been working on developing my skills in ML techniques and algorithms.
                {/* <span className=' text-teal-500'> ML skills, Android and Web</span> development ? */}
              </p>
          </div>

          {/* Cards */}
          <div className='lg:flex gap-5 '>
          <div className=' font-productsans text-center p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light 
           dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={lang} width={100} height={100}/>
            </div>
            <h3 className=' text-2xl pt-8 pb-2'>Languages Known</h3>
            <p className='py-2'>
              Using multitudes of languages to accomplish tasks and leveraging best features of each one!
            </p>

            <div className='container mx-auto font-productsans pt-5'>
              <div className=' grid-cols-2 space-y-2 lg:space-y-0 grid gap-2
              sm:grid-cols-2 md:grid-cols-2'>
                  
                  <Blocks skill="Python" image="https://cdn.simpleicons.org/python/3776AB" />
                  <Blocks skill="Kotlin" image="https://cdn.simpleicons.org/kotlin/7F52FF" />
                  <Blocks skill="JavaScript" image="https://cdn.simpleicons.org/javascript/F7DF1E" />
                  <Blocks skill="SQL" image="https://cdn.simpleicons.org/sqlite/003B57" />

              </div>
            </div>
            
          </div>

          <div className=' font-productsans text-center  p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light
            dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={machine} width={100} height={100}/>
            </div>
            <h3 className=' text-2xl pt-8 pb-2'>Frameworks</h3>
            <p className='py-2 dark:text-white'>
              Set of libraries and techniques I use to implement and develop machine learning models.
            </p>

            <div className='container mx-auto font-productsans'>
              <div className=' lg:grid-cols-3 p-5 space-y-2 lg:space-y-0 grid gap-2 grid-cols-2 '>

                  <Blocks skill="TensorFlow" image="https://cdn.simpleicons.org/tensorflow/FF6F00"/>
                  <Blocks skill="PyTorch" image="https://cdn.simpleicons.org/pytorch/EE4C2C" />
                  <Blocks skill="Scikit-Learn" image="https://cdn.simpleicons.org/scikitlearn/F7931E" />
                  <Blocks skill="Firebase" image="https://cdn.simpleicons.org/firebase/FFCA28" />
                  <Blocks skill="React" image="https://cdn.simpleicons.org/react/61DAFB" />
                  <Blocks skill="NodeJS" image="https://cdn.simpleicons.org/nodedotjs/339933" />

              </div>
              </div>
          </div>

          <div className=' font-productsans text-center  p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light 
           dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={tools} width={100} height={100}/>
            </div>
            <h3 className='  text-2xl pt-8 pb-2'>Tools</h3>
            <p className='py-2 dark:text-white'>
              Tools for  data pre-processing, visualization, model development and deployment.
            </p>

            <div className='container ml-auto font-productsans'>
              <div className=' grid-cols-3 p-5 space-y-2 lg:space-y-0 grid gap-2'>

                  <div className=' text-center rounded-lg flex-1 w-full col-span-2
                  bg-hover-bg-light group-hover:bg-card-light  
                  dark:bg-hover-bg-dark dark:group-hover:bg-hover-bg-light dark:group-hover:text-gray-700'>
                    <div className='flex justify-center mb-2 mt-5 basis-1/3' >
                      <img height="32" width="32" src="https://cdn.simpleicons.org/jupyter/F37626" />
                    </div>
                    <p className='pb-2' >Jupyter Notebook</p>
                  </div>

                  <Blocks skill="Studio" image="https://cdn.simpleicons.org/android/3DDC84" />
                  <Blocks skill="Colab" image="https://cdn.simpleicons.org/googlecolab/F9AB00" />
                  <Blocks skill="Anaconda" image="https://cdn.simpleicons.org/anaconda/44A833" />
                  <Blocks skill="Git" image="https://cdn.simpleicons.org/git/F05032" />

              </div>
              </div>

            {/* <h4 className=' text-teal-600 py-4'>Frameworks and Tools I use</h4>
            <p className=' text-gray-800 py-1'>TensorFlow</p>
            <p>PyTorch</p>
            <p>Google Colab</p> */}
          </div>
          </div>
          
        </section>

        {/* PORTFOLIO SECTION */}
        <section>
          
          <div id="my-projects" className=' font-productsans pt-10'>
          <h3 className='text-center lg:text-start text-5xl pt-10 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark '>Portfolio</h3>
          <p className=' text-md py-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'>
          As a Machine Learning Engineer, my projects include a wide range of applications of ML techniques - computer vision, natural language processing, prediction, and reinforcement learning.
          Along with these, I enjoy building mobile applications and webapps using popular frameworks like React.  
          <br></br>
          These following projects highlight my ability to apply my knowledge to real-world problems and to deliver value to business and organizations.
          </p>
          </div>

          <SectionPortfolio />

          <a href='https://github.com/Leonardo-daVinci' target="_blank" rel="noreferrer">
          <div className=' flex justify-end'>
          <div className='font-productsans text-center rounded-2xl mb-10 group p-5 lg:w-1/2
          flex items-center
           bg-card-light hover:bg-hover-bg-light
            dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <h3 className='text-center w-full text-2xl'>View all my projects and their code here</h3>
            <BsArrowRight className=' text-2xl ml-5'/>
            </div>
          </div>
          </a>
          
        </section>

        {/* EDUCATION */}
        <section>
        <div id="my-academics" className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-10 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark'>Academic background</h3>
              <p className=' text-md pt-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
                Summary of my Masters Degree <span>&#40;</span>ongoing<span>&#41;</span> and Bachelors Degree.
              </p>
          </div>

          <div className=' font-productsans flex flex-col gap-5 py-5 lg:flex-row lg:flex-wrap'>
          
            <div className=' basis-1/3 flex-1 group bg-card-light rounded-lg hover:bg-hover-bg-light
            dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
              
              <div className=' px-4 py-4 text-center'>
              <h3 className="text-2xl pt-4 text-gray-800 dark:text-white">Masters in Computer Science</h3>
              <p className='text-xl pb-4 dark:text-white'>University of Southern California, Los Angeles, US</p>
              </div>
              <div className='container mx-auto font-productsans'>
                <div className=' grid-cols-1 p-5 space-y-2 lg:space-y-0 lg:grid lg:gap-2 lg:grid-row-2'>

                <Course 
                  id="DSCI-552" name="Machine Learning for Data Science"
                  des="Practical applications of machine learning techniques to real-world problems. 
                  Uses in data mining and recommendation systems and for building adaptive user interfaces."
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Mohammad Reza Rajati</span></p>}
                />

                <Course 
                  id="CSCI-585" name="Database Systems"
                  des="Database system architecture, conceptual database models - semantic, object-oriented, logic-based, and relational databases, 
                  user and program interfaces,  database system implementation, integrity, security, concurrency and recovery. 
                  Requires  Knowledge of relational databases, SQL, relational algebra and physical database design."
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Sathyanaraya Raghavachary</span></p>}
                />

                <Course 
                  id="CSCI-544" name="Applied Natural Language Processing"
                  des="Introduction to key components of human language technologies, including information extraction, sentiment analysis, question answering, machine translation."
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Ron Artstein and Prof. Mohammad Rostami</span></p>}
                />

                <Course 
                  id="CSCI-567" name="Machine Learning"
                  des="Statistical methods for building intelligent and adaptive systems that improve performance from experiences. 
                  Focus on theoretical understanding of these methods and their computational implications. 
                  Requires Undergraduate level training or coursework in linear algebra, multivariate calculus, basic probability and statistics"
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Yan Liu</span></p>}
                />

                <Course 
                  id="CSCI-571" name="Web Technologies"
                  des="Advanced study of programming languages with application to the Web. Languages for client-side and server-side processing. 
                  Examples taken from: HTML, Java, JavaScript, Perl, XML and others"
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Marco Papa</span></p>}
                />

                <Course 
                  id="CSCI-561" name="Foundations of Artificial Intelligence"
                  des="Foundations of symbolic intelligent systems, search, logic, knowledge representation, planning, learning."
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Wei-Min Shen</span></p>}
                />

                <Course 
                  id="CSCI-570" name="Analysis of Algorithms"
                  des="Explores fundamental techniques such as recursion, Fourier transform ordering, dynamic programming for efficient algorithm construction. 
                  Examples include arithmetic, algebraic, graph, pattern matching, sorting, searching algorithms."
                  prof={<p>Taught by <span className=" text-my-text-light dark:text-my-text-dark">Prof. Shahriar Shamsian</span></p>}
                />
                  

                </div>
              </div>
            </div>

            <div className=' basis-1/3 flex-1 group bg-card-light rounded-lg hover:bg-hover-bg-light
            dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
              
              <div className=' px-4 py-4 text-center'>
              <h3 className="text-2xl pt-4 text-gray-800 dark:text-white">Bachelors in Computer Engineering</h3>
              <p className='text-xl pb-4 dark:text-white'>MES College of Engineering, Pune, India</p>
              </div>
              <div className='container mx-auto font-productsans'>
                <div className=' grid-cols-1 p-5 space-y-2 lg:space-y-0 lg:grid lg:gap-2 lg:grid-row-2'>

                <Course 
                  id="BE" name="Final Year Engineering"
                  des={
                    <div className='container mx-auto font-productsans'>
                        <div className=' lg:grid-cols-2 p-2 space-y-2 lg:space-y-0 lg:grid lg:gap-2'>
                          <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 7</p>
                          <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 8</p>
                          <p className='lg:hidden text-md text-my-text-light dark:text-my-text-dark'>Semester 7 and 8</p>
                          <p>Artificial Intelligence and Robotics</p>
                          <p>Machine Learning</p>
                          <p>Data Analytics</p>
                          <p>Human Computer Interface</p>
                          <p>Data Mining and Warehousing</p>
                          <p>Soft Computing and Optimization</p>
                          <p>High Performance Computing</p>
                          <p>Information and Cyber Security</p>
                          <p>Software Testing and QA</p>
                          <p>Final Year Project</p>
                        </div>
                      </div>
                  }
                />

                <Course 
                  id="TE" name="Third Year Engineering"
                  des={
                    <div className='container mx-auto font-productsans'>
                        <div className=' grid-cols-2 p-5 space-y-2 lg:space-y-0 lg:grid lg:gap-2 lg:grid-row-2'>
                        <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 5</p>
                          <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 6</p>
                          <p className='lg:hidden text-md text-my-text-light dark:text-my-text-dark'>Semester 5 and 6</p>
                          <p>Theory of Computation</p>
                          <p>Design and Analysis of Algorithms</p>
                          <p>Database Management Systems</p>
                          <p>System Prog. and Operating Systems</p>
                          <p>Software Engg. and Project Mgmt.</p>
                          <p>Embedded Systems and IOT</p>
                          <p>Info. Systems and Engg Economics</p>
                          <p>Software Modelling and Design</p>
                          <p>Computer Networks</p>
                          <p>Web Technology</p>
                        </div>
                      </div>
                  }
                />

                <Course 
                  id="SE" name="Second Year Engineering"
                  des={
                    <div className='container mx-auto font-productsans'>
                        <div className=' grid-cols-2 p-5 space-y-2 lg:space-y-0 lg:grid lg:gap-2 lg:grid-row-2'>
                        <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 3</p>
                          <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 4</p>
                          <p className='lg:hidden text-md text-my-text-light dark:text-my-text-dark'>Semester 3 and 4</p>
                          <p>Discrete Mathematics</p>
                          <p>Engineering Mathematics III</p>
                          <p>Data Structures and Algorithms</p>
                          <p>Advanced Data Structures</p>
                          <p>Object Oriented Programming</p>
                          <p>Principles of Prog. Languages</p>
                          <p>Digital Electronics and Logic Design</p>
                          <p>Computer Graphics</p>
                          <p>Comp. Organization and Arch.</p>
                          <p>Microprocessor</p>
                        </div>
                      </div>
                  }
                />

                <Course 
                  id="FE" name="First Year Engineering"
                  des={
                    <div className='container mx-auto font-productsans'>
                        <div className=' grid-cols-2 p-5 space-y-2 lg:space-y-0 lg:grid lg:gap-2 lg:grid-row-2'>
                        <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 1</p>
                          <p className='hidden lg:block text-2xl text-my-text-light dark:text-my-text-dark'>Semester 2</p>
                          <p className='lg:hidden text-md text-my-text-light dark:text-my-text-dark'>Semester 1 and 2</p>
                        <p>Engineering Mathematics I</p>
                        <p>Engineering Mathematics II</p>
                        <p>Engineering Physics</p>
                        <p>Engineering Chemistry</p>
                        <p>Fundamentals of Prog. Lang. I</p>
                        <p>Fundamentals of Prog. Lang. II</p>
                        <p>Basic Electronics Engg.</p>
                        <p>Basic Electrical Engg.</p>
                        <p>Basic Civil and Environment Engg</p>
                        <p>Basic Mechanical Engg</p>
                        <p>Engineering Graphics I</p>
                        <p>Engineering Graphics II</p>
                        <p>Workshop Practices</p>
                        <p>Physical Education</p>

                        </div>
                      </div>
                  }
                />

                </div>
              </div>
            </div>
            
          </div>
          </section>

            {/* MERITS */}
          <section>
          <div id="my-merits" className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-10 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark'>Certifications and Achievements</h3>
              <p className=' text-md pt-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
                This section includes certifications in machine learning, deep learning and data science, recognition in hackathons, competitions and DevFests, and awards and publications.
                 <br></br>  It showcases my dedication to continuously learn and improve my skills.
              </p>
          </div>

          <Carousel />

          <Link href="/details">
          <div className=' flex justify-end'>
          <div className='font-productsans text-center rounded-2xl mb-10 group p-5 lg:w-1/2
           bg-card-light hover:bg-hover-bg-light
           flex items-center
            dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
             
            <h3 className='text-center w-full text-2xl'>
              View all certifications and achievements here</h3>
            <BsArrowRight className=' text-2xl ml-5'/>
            </div>
          </div>
          </Link>
        </section>

        
        {/* EXTRAS */}
        <section>
        <div id="my-hobbies" className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-10 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark'>Co-curricular Activities</h3>
              <p className=' text-md pt-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
                This section includes my involvement in student clubs, hobbies and other personal info. 
              </p>
          </div>

          <div className='container mx-auto'>
                  <div className='grid-cols-3 pt-10 space-y-2 lg:space-y-0 lg:grid lg:gap-5'>
                      
                      <div className=' font-productsans text-center p-5 rounded-xl flex flex-col justify-center group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={club} width={100} height={100}/>
                        </div>
                        <h3 className=' text-2xl pt-4 pb-2'>Student Mentor</h3>
                        <p className='pb-2'>
                          Google Developer Student Clubs <br></br>MES College of Engineering
                        </p>
                        </div>
                        

                      <div className=' font-productsans p-5 rounded-xl flex-1 group col-span-2 my-auto
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        
                        <Bullet des="Taught students concepts of Deep Learning and implementation of Neural Networks in TensorFlow."/>
                        <Bullet des="Directed students for building mobile applications in Android using Android Studio."/>
                        <Bullet des="Conducted intercollege technical event for Google Cloud workshop and directed students in Machine Learning Track." />
                        <Bullet des="Lead college team for Google's 'Build for India' competition." />

                      </div>
                  </div>
            </div>

            <div className='container mx-auto'>
                  <div className='grid-cols-3 pt-5 space-y-2 lg:space-y-0 lg:grid lg:gap-5'>
                      
                      <div className=' font-productsans text-center p-5 rounded-xl flex flex-col justify-center group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={ais} width={100} height={100}/>
                        </div>
                        <h3 className=' text-2xl pt-4 pb-2'>Director</h3>
                        <p className='pb-2'>
                          Association of Indian Students <br></br> University of Southern California
                        </p>
                      </div>

                      <div className=' font-productsans p-5 rounded-xl flex-1 group col-span-2
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        
                        <Bullet des="Organized cultural events such as Diwali, Holi, Garba Night, etc. for over a thousand students in the university." />
                        <Bullet des="Designed posters and other publicity campaign materials for the events above. " />
                        <Bullet des="Represented India in the International Day Event organized by the university." />
                        <Bullet des="Performed group dance for the events of Holi and Diwali." />

                      </div>
                  </div>
            </div>

            <div className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-10 text-my-text-light md:text-4xl dark:text-my-text-dark'>Hobbies</h3>
              <p className=' text-md pt-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
              My hobbies section includes a variety of activities that I enjoy and that demonstrate my diverse interests. It provides a glimpse into my personality and demonstrates my ability to balance work and leisure.
              </p>
          </div>

          {/* Hobbies section */}
          <div className='container mx-auto'>
                  <div className='lg:grid-cols-3 pt-10 pb-20 space-y-2 lg:space-y-0 grid lg:gap-5
                  grid-cols-2 gap-2
                  md:gap-2 sm:gap-2'>
                      
                      <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={reading} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Reading Science Fiction, Thriller books.</h3>
                        </div>

                        <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={gym} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Excercising at the Gym</h3>
                        </div>

                        <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={french} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Practicing speaking and writing French</h3>
                        </div>

                        <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={muay} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Learning martial arts form Muay Thai</h3>
                        </div>

                        <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={dance} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Participating in Group Dances</h3>
                        </div>

                        <div className=' font-productsans text-center p-5 rounded-xl flex-1 group
                      bg-card-light hover:bg-hover-bg-light 
                      dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
                        <div className='flex justify-center'>
                        <Image src={art} width={100} height={100}/>
                        </div>
                        <h3 className=' text-xl pt-4 pb-2'>Calligraphy and making digital art</h3>
                        </div>
                        
                  </div>
            </div>




        </section>


        {/* <section>
          <div className=' text-center p-10 font-productsans'>
              <h3 className='text-5xl py-2 text-teal-600 md:text-6xl dark:text-teal-400'>
              <Link href="/timeline"> Go to timeline </Link>
              </h3>

          </div>

        </section> */}

        

      </main>
    </div>
  )
}
