import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillGithub} from 'react-icons/ai'
import {BsArrowRight} from "react-icons/bs"
// import pdf from "../public/Akshit_Resume.pdf"

import Image from 'next/image'
import avatar2 from "../public/avatar2.png"

import lang from '../public/lang.png'
import machine from '../public/machine.png'
import tools from '../public/tools.png'

import {useState} from 'react'
import Link from 'next/link'
import SideNavBar from '../components/SideNavbar'
import Blocks from '../components/Legos/Blocks'
import Carousel from '../components/Legos/Carousel'
import Bullet from '../components/Legos/Bullet'
import SectionPortfolio from '../components/sections/section-portfolio'
import SectionEducation from '../components/sections/section-education'
import SectionMerits from '../components/sections/section-merits'
import SectionExtras from '../components/sections/section-extras'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div id="home" className={darkMode ? "dark" : ""}>
      <Head>
        <title>Akshit Keoliya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}/>
      </Head>
      <SideNavBar/>

      <div className="lg:hidden fixed top-0 w-full z-10 bg-white dark:bg-[#1f1f1f]">
        <div className=" p-5 flex justify-end dark:text-white">
        <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" />
        </div>
      </div>

      <main className=' bg-white px-5 md:px-5 lg:ml-20 lg:px-40 dark:bg-[#1f1f1f]'>

        {/* HOMEPAGE SECTION */}

        <nav className='hidden lg:block fixed z-10 top-10 right-4 lg:right-10 justify-between dark:text-white'>
          <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=' cursor-pointer text-2xl
              '/></li>
          </ul>
        </nav>

        <section className='lg:pt-20 pt-16 min-h-screen md:min-h-fit'>
        
        {/* Navigation Section */}
        
          {/* Introduction */}

          <div className='flex justify-center mx-auto'>
          <div className='lg:hidden relative rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading='eager' priority='true' />
          </div>
          </div>

          <div className=' flex justify-center items-center mx-auto md:mb-12 md:pb-10'>
          <div className='hidden lg:block relative bg-gradient-to-b from-my-text-light to-my-text-dark rounded-full w-80 h-80 lg:mt-10 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading='eager' priority='true' />
          </div>
          
          <div className='px-20'>
          <div className=' text-center p-5 lg:p-10 font-productsans'>
            <h2 className=' text-4xl lg:text-6xl py-2 text-my-text-light md:text-6xl dark:text-my-text-dark'>Akshit Abhay Keoliya</h2>
            <h3 className=' text-xl pt-2 md:text-3xl dark:text-white'>Machine Learning Enthusiast and Developer</h3>
            <p className=' text-md py-5 lg:leading-8 text-gray-800v md:text-xl max-w-xl mx-auto dark:text-gray-200'>
            Master<span>&apos;</span>s in Computer Science, Artificial Intelligence at 
            <span className='text-[#0b57d0] dark:text-[#a8c7fa]'><a href='https://www.usc.edu/'> USC</a></span>.
            <br></br>
            Excited to apply my knowledge to real-world problems and help organizations improve their operations and decision-making through machine learning!
              </p>

              <div className='pt-5'>
              <a className=' bg-my-text-light dark:bg-my-text-dark text-white dark:text-gray-800
              text-2xl
              font-productsans px-8 py-4 rounded-full' 
              href='/portfolio/Akshit_Keoliya_Resume.pdf' target="_blank" rel="noreferrer">
                Curriculum Vitae
              </a>
              </div>

          </div>

          {/* Contacts */}

          <div className=' text-5xl flex justify-center gap-10 py-8 text-gray-600 dark:text-gray-400'>
            <a href='https://www.linkedin.com/in/akshit-keoliya'><AiFillLinkedin /></a>  
            <a href='https://github.com/Leonardo-daVinci'><AiFillGithub /></a>
            <a href='https://twitter.com/AkshitAbhay'><AiFillTwitterCircle /></a>
            <a href='https://www.instagram.com/machine.learning.chef'><AiFillInstagram /></a>
          </div>
          </div>

          </div>

          {/* Image */}

          {/* <div className='lg:hidden relative mx-auto bg-gradient-to-b from-my-text-light to-my-text-dark rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
          <Image src={avatar2} alt='Avatar' fill="true" objectFit='cover' loading="eager" priority='true' />
          </div> */}

        </section>

        {/* SKILLS SECTION */}

        <section>
          <div id="my-skills" className=' font-productsans pt-10'>
              <h3 className='text-center lg:text-start text-5xl pt-5 pb-2 text-my-text-light md:text-4xl dark:text-my-text-dark'>My skills</h3>
              <p className=' text-md py-5 leading-8 text-gray-800v md:text-xl dark:text-gray-200'> 
              I have a strong background in mathematics and computer science and 
              have been working on developing my skills in ML techniques and algorithms.
                {/* <span className=' text-teal-500'> ML skills, Android and Web</span> development ? */}
              </p>
          </div>

          {/* Cards */}
          <div className='lg:flex gap-5 '>
          <div className=' font-productsans text-center p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light 
           dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={lang} width={100} height={100}/>
            </div>
            <h3 className=' text-2xl pt-8 pb-2'>Languages Known</h3>
            <p className='py-2'>
              Using multitudes of languages to accomplish tasks and leveraging best features of each one!
            </p>

            <div className='container mx-auto font-productsans pt-5'>
              <div className=' grid-cols-2 space-y-2 lg:space-y-0 grid gap-2
              sm:grid-cols-2 md:grid-cols-2'>
                  
                  <Blocks skill="Python" image="https://cdn.simpleicons.org/python/3776AB" />
                  <Blocks skill="Kotlin" image="https://cdn.simpleicons.org/kotlin/7F52FF" />
                  <Blocks skill="JavaScript" image="https://cdn.simpleicons.org/javascript/F7DF1E" />
                  <Blocks skill="SQL" image="https://cdn.simpleicons.org/sqlite/003B57" />

              </div>
            </div>
            
          </div>

          <div className=' font-productsans text-center  p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light
            dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={machine} width={100} height={100}/>
            </div>
            <h3 className=' text-2xl pt-8 pb-2'>Frameworks</h3>
            <p className='py-2 dark:text-white'>
              Set of libraries and techniques I use to implement and develop machine learning models.
            </p>

            <div className='container mx-auto font-productsans'>
              <div className=' lg:grid-cols-3 p-5 space-y-2 lg:space-y-0 grid gap-2 grid-cols-2 '>

                  <Blocks skill="TensorFlow" image="https://cdn.simpleicons.org/tensorflow/FF6F00"/>
                  <Blocks skill="PyTorch" image="https://cdn.simpleicons.org/pytorch/EE4C2C" />
                  <Blocks skill="Scikit-Learn" image="https://cdn.simpleicons.org/scikitlearn/F7931E" />
                  <Blocks skill="Firebase" image="https://cdn.simpleicons.org/firebase/FFCA28" />
                  <Blocks skill="React" image="https://cdn.simpleicons.org/react/61DAFB" />
                  <Blocks skill="NodeJS" image="https://cdn.simpleicons.org/nodedotjs/339933" />

              </div>
              </div>
          </div>

          <div className=' font-productsans text-center  p-5 rounded-xl my-10 flex-1 group
           bg-card-light hover:bg-hover-bg-light 
           dark:text-white dark:bg-card-dark dark:hover:bg-hover-bg-dark'>
            <div className='flex justify-center'>
            <Image src={tools} width={100} height={100}/>
            </div>
            <h3 className='  text-2xl pt-8 pb-2'>Tools</h3>
            <p className='py-2 dark:text-white'>
              Tools for  data pre-processing, visualization, model development and deployment.
            </p>

            <div className='container ml-auto font-productsans'>
              <div className=' grid-cols-3 p-5 space-y-2 lg:space-y-0 grid gap-2'>

                  <div className=' text-center rounded-lg flex-1 w-full col-span-2
                  bg-hover-bg-light group-hover:bg-card-light  
                  dark:bg-hover-bg-dark dark:group-hover:bg-hover-bg-light dark:group-hover:text-gray-700'>
                    <div className='flex justify-center mb-2 mt-5 basis-1/3' >
                      <img height="32" width="32" src="https://cdn.simpleicons.org/jupyter/F37626" />
                    </div>
                    <p className='pb-2' >Jupyter Notebook</p>
                  </div>

                  <Blocks skill="Studio" image="https://cdn.simpleicons.org/android/3DDC84" />
                  <Blocks skill="Colab" image="https://cdn.simpleicons.org/googlecolab/F9AB00" />
                  <Blocks skill="Anaconda" image="https://cdn.simpleicons.org/anaconda/44A833" />
                  <Blocks skill="Git" image="https://cdn.simpleicons.org/git/F05032" />

              </div>
              </div>

            {/* <h4 className=' text-teal-600 py-4'>Frameworks and Tools I use</h4>
            <p className=' text-gray-800 py-1'>TensorFlow</p>
            <p>PyTorch</p>
            <p>Google Colab</p> */}
          </div>
          </div>
          
        </section>

        {/* PORTFOLIO SECTION */}
        <section>

          <SectionPortfolio />
          
        </section>

        {/* EDUCATION */}
        <section>

          <SectionEducation />

        </section>

            {/* MERITS */}
          <section>

            <SectionMerits />

        </section>

        
        {/* EXTRAS */}
        <section>

            <SectionExtras />

        </section>


        {/* <section>
          <div className=' text-center p-10 font-productsans'>
              <h3 className='text-5xl py-2 text-teal-600 md:text-6xl dark:text-teal-400'>
              <Link href="/timeline"> Go to timeline </Link>
              </h3>

          </div>

        </section> */}

        

      </main>
    </div>
  )
}
